"""
Meta Research — Guardian module.

Weekly: researches entirely new agent ideas, techniques, and capabilities.
Writes findings to brain/research/ and surfaces promising ideas to Suhail.

This is the "curiosity" module — like a human who reads widely and
makes unexpected creative connections.
"""

import os
import json
import subprocess
from datetime import datetime, timedelta
import logging

META_LOG = "/home/r2d2/guardian/meta_research_log.json"
RESEARCH_DIR = "/home/r2d2/brain/research"
log = logging.getLogger("guardian")

RESEARCH_TOPICS = [
    # Agent techniques
    "AI agent memory systems 2026 persistent context",
    "multi-agent collaboration frameworks 2026",
    "AI agent self-improvement techniques",
    "autonomous agent planning reasoning 2026",
    # Domain-specific improvements
    "AI career coaching tools 2026 job market",
    "automated code review AI techniques 2026",
    "AI news curation personalization 2026",
    # Emerging tech relevant to Suhail's stack
    "Bun Elysia performance benchmarks 2026",
    "React Native 2026 new features performance",
    "LoRa Meshtastic mesh networking applications",
    "ONDC WhatsApp commerce India 2026 updates",
    # Creativity + productivity
    "second brain digital productivity 2026",
    "building in public strategies engineer founders 2026",
    "AI SaaS pricing models 2026 India market"
]


def load_log():
    if os.path.exists(META_LOG):
        with open(META_LOG) as f:
            try:
                return json.load(f)
            except:
                pass
    return {"last_run": None, "topics_done": []}


def save_log(data):
    with open(META_LOG, "w") as f:
        json.dump(data, f, indent=2, default=str)


def run_meta_research():
    """Weekly meta-research: learn new things, write to brain, surface gems."""
    data = load_log()
    now = datetime.now()

    last_run = data.get("last_run")
    if last_run:
        last_dt = datetime.fromisoformat(last_run)
        if (now - last_dt).days < 7:
            return

    # Pick 3 topics not done recently
    topics_done = data.get("topics_done", [])
    available = [t for t in RESEARCH_TOPICS if t not in topics_done[-10:]]
    if not available:
        available = RESEARCH_TOPICS
        data["topics_done"] = []

    selected = available[:3]
    log.info(f"META RESEARCH: researching {selected}")

    results = []
    for topic in selected:
        try:
            result = subprocess.run(
                ["python3", "/home/r2d2/tools/websearch.py", "--summary", topic],
                capture_output=True, text=True, timeout=30
            )
            if result.stdout.strip():
                results.append(f"### {topic}\n{result.stdout[:600]}")
        except:
            pass

    if not results:
        data["last_run"] = now.isoformat()
        save_log(data)
        return

    # Write to brain research dir
    os.makedirs(RESEARCH_DIR, exist_ok=True)
    date_str = now.strftime("%Y-%m-%d")
    research_file = f"{RESEARCH_DIR}/{date_str}-meta-research.md"

    content = f"# Meta Research — {date_str}\n\n"
    content += f"Topics: {', '.join(selected)}\n\n"
    content += "\n\n".join(results)
    content += "\n\n---\n*Generated by Guardian Meta Research*\n"

    with open(research_file, "w") as f:
        f.write(content)

    # Ask 3PO to synthesize insights and identify new agent ideas
    synthesis_prompt = f"""You are the Meta Research Synthesizer for R2D2's agent ecosystem.

Read this research:
---
{chr(10).join(results)[:3000]}
---

Also read the current agent roster at /home/r2d2/brain/agents/README.md

Your tasks:
1. Extract 3-5 KEY INSIGHTS that could improve R2D2's current agents (Guardian, Maxwell, ARIA, 3PO)
2. Identify 1-2 NEW AGENT IDEAS that would genuinely add value for Suhail
   - Each idea needs: name, purpose, how it works, why it's valuable NOW
3. Identify 1-2 techniques R2D2 should adopt immediately (no agent needed, just behavior change)

Write your synthesis to: {research_file.replace('.md', '-synthesis.md')}
Format as clean markdown with sections: Insights, New Agent Ideas, Immediate Techniques

Then sync to brain:
git -C /home/r2d2/brain add -A
git -C /home/r2d2/brain commit -m "research: weekly meta-research synthesis {date_str}"
git -C /home/r2d2/brain push origin master

If a new agent idea is compelling enough (score it 1-10, implement if 8+):
- Create the spec at /home/r2d2/brain/agents/<name>/README.md
- Add to agent registry in /home/r2d2/guardian/agent_evolver.py
- Notify Suhail: openclaw message send --channel whatsapp --target +14699941765 --message "💡 New agent idea: [name] — [1 sentence description]. Score: X/10. Shall I build it?"

Print: META_SYNTHESIS_DONE: [1 sentence summary of most interesting finding]
"""

    result = subprocess.Popen(
        ["claude", "--permission-mode", "bypassPermissions", "--print", synthesis_prompt],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL
    )

    # Update log
    data["topics_done"] = (topics_done + selected)[-20:]
    data["last_run"] = now.isoformat()
    save_log(data)

    log.info(f"META RESEARCH: done, synthesis dispatched")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run_meta_research()
    print("Meta research triggered")
